name: varrna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.14
  - bedtools=2.30
  - fastqc=0.11
  - gatk4=4.2.6.1
  - numpy=1.23.1
  - pandas=1.4.3
  - perl=5.32
  - python=3.9
<<<<<<< HEAD
  - snakemake=7.9.0
  - pyfaidx=0.8.1.2
  - xgboost=2.1.1
  - scikit-learn=1.5.2
=======
  - scikit-learn=1.1.2
  - xgboost=2.1.1
  - snakemake=7.9.0
  - pyfaidx=0.8.1.2
>>>>>>> 12f0344e5f277c2fe06efccc85d0fa7a9a28a195
